export enum ErrorCode {
  // Authentication & Authorization
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_DISABLED = 'USER_DISABLED',

  // Product
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_DISABLED = 'PRODUCT_DISABLED',
  PRODUCT_SLUG_EXISTS = 'PRODUCT_SLUG_EXISTS',
  VERSION_NOT_FOUND = 'VERSION_NOT_FOUND',

  // Purchase
  PURCHASE_INVALID = 'PURCHASE_INVALID',
  PURCHASE_NOT_FOUND = 'PURCHASE_NOT_FOUND',
  PURCHASE_ALREADY_CLAIMED = 'PURCHASE_ALREADY_CLAIMED',
  PURCHASE_PRODUCT_MISMATCH = 'PURCHASE_PRODUCT_MISMATCH',
  MARKETPLACE_VERIFICATION_FAILED = 'MARKETPLACE_VERIFICATION_FAILED',

  // License
  LICENSE_NOT_FOUND = 'LICENSE_NOT_FOUND',
  LICENSE_INVALID = 'LICENSE_INVALID',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  LICENSE_SUSPENDED = 'LICENSE_SUSPENDED',
  LICENSE_REVOKED = 'LICENSE_REVOKED',
  LICENSE_BLOCKED = 'LICENSE_BLOCKED',

  // Activation & Validation
  ACTIVATION_LIMIT_REACHED = 'ACTIVATION_LIMIT_REACHED',
  ACTIVATION_NOT_FOUND = 'ACTIVATION_NOT_FOUND',
  ACTIVATION_DEACTIVATED = 'ACTIVATION_DEACTIVATED',
  DOMAIN_MISMATCH = 'DOMAIN_MISMATCH',
  INSTALLATION_MISMATCH = 'INSTALLATION_MISMATCH',
  PRODUCT_MISMATCH = 'PRODUCT_MISMATCH',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // Distribution & Security
  UPDATE_NOT_ALLOWED = 'UPDATE_NOT_ALLOWED',
  DOWNLOAD_NOT_ALLOWED = 'DOWNLOAD_NOT_ALLOWED',
  RATE_LIMITED = 'RATE_LIMITED',
  BLOCKED = 'BLOCKED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTEGRATION_TESTS_REQUIRED = 'INTEGRATION_TESTS_REQUIRED',
}
